import type { Metadata } from "next";


import Navbar from "./_components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "cosas-sueltas",
  description: "Generated by appncy",
};

// eslint-disable-next-line react/function-component-definition
const RootLayout = ({children}: {children: React.ReactNode}) => {
  return (
    <html lang="en">
      <body className="light container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 font-sans antialiased bg-gray-900">
       <Navbar/>
        <main className="py-24">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} Cosas sueltas <span className="text-xs"> by Adolfo</span>
        </footer>
      </body>
    </html>
  );
};

export default RootLayout;
