import type { Metadata } from "next";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "cosas-sueltas",
  description: "Generated by appncy",
};

const RootLayout = ({children}: {children: React.ReactNode}) => {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-900 text-white">
        <Navbar />
        <main className="flex-grow container mx-auto px-4 py-24">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;